stages:
  - run tests

variables:
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pypoetry"

run tests:
  stage: run tests
  tags:
    - prod_docker_run
  image: python:3.11-slim
  cache:
    key:
      files:
        - poetry.lock
    paths:
      - .cache/pypoetry
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install
    - source .venv/bin/activate
    - pip install pytest-xdist
  script:
    - pytest -n auto
