Value Filldown acl_type (ip)
Value Filldown acl_name ([\w+-]+)
Value seq_num (\d+)
Value fw_action (permit|deny)
Value protocol (esp|gre|gtpc|gtpu|icmp|igmp|ip|ipip|nvgre|tcp|udp|vxlan|\d+)
Value network_id (\d+)
Value src_ip (any|[\.\d]+)
Value src_mask ([\.0254]+)
Value dst_ip (any|[\.\d]+)
Value dst_mask ([\.0254]+)
Value dport (\d+)
Value dport_end (\d+)
Value sport (\d+)
Value sport_end (\d+)
Value length (\d+)
Value length_end (\d+)
Value dscp (\d+)
Value vlan (\d+)
Value igmp_type (\d+)
Value icmp_type (\d+)
Value icmp_code (\d+)
Value fragment (morefragment|dontfragment)
Value ack (ack)
Value cwr (cwr)
Value ece (ece)
Value fin (fin)
Value push (push)
Value reset (reset)
Value sync (sync)
Value urg (urg)
Value log (log)
Value count (count)

Start
  ^${acl_type}\s+access-list\s+${acl_name}\s*
  ^\s*seq\s+${seq_num}\s+${fw_action}\s+${protocol}\s*(${network_id})?\s+${src_ip}\s*(${src_mask})?\s+${dst_ip}\s*(${dst_mask})?\s*(dport\s+${dport})?\s*(dport-end\s+${dport_end})?\s*(sport\s+${sport})?\s*(sport-end\s+${sport_end})?\s*(length\s+${length})?\s*(length-end\s+${length_end})?\s*(dscp\s+${dscp})?\s*(vlan\s+${vlan})?\s*(igmp-type\s+${igmp_type})?\s*(icmp-type\s+${icmp_type})?\s*(icmp-code\s+${icmp_code})?\s*(${fragment})?\s*(${ack})?\s*(${cwr})?\s*(${ece})?\s*(${fin})?\s*(${push})?\s*(${reset})?\s*(${sync})?\s*(${urg})?\s*(${log})?\s*(${count})?\s* -> Record
  #^\s*seq\s+${seq_num}\s+${fw_action}\s+${protocol}\s+${src_ip}\s*(${src_mask})?\s+${dst_ip}\s*(${dst_mask})?\s*(dport\s+${dport})?\s*(dport-end\s+${dport_end})?\s*(sport\s+${sport})?\s*(sport-end\s+${sport_end})?\s*(length\s+${length})?\s*(length-end\s+${length_end})?\s*(dscp\s+${dscp})?\s*(vlan\s+${vlan})?\s*(igmp-type\s+${igmp_type})?\s*(icmp-type\s+${icmp_type})?\s*(icmp-code\s+${icmp_code})?\s*(${fragment})?\s*(${ack})?\s*(${fin})?\s*(${push})?\s*(${sync})?\s*(${reset})?\s*(${ece})?\s*(${cwr})?\s*(${urg})?\s*(${log})?\s*(${count})?\s* -> Record
